# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test 
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        # Remote host
        REMOTE_HOST: ${{ secrets.SERVER_IP }}
        # Remote user
        REMOTE_USER: ${{ secrets.USERNAME }}
        # Remote port
        REMOTE_PORT: ${{ secretes.SERVER_PORT }}
        # Source directory
        SOURCE: "dist/"
        # Target directory
        TARGET: ${{ secretes.SERVER_DESTINATION }}
        # Arguments to pass to rsync
        ARGS: "-avzr --delete"
